language: python
sudo: false

python:
- '3.6'
- '2.7.11'

install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- py.test --pyargs fishersapi
